export const sdkInitializationProperties = [
    {
      'Property Name': 'appId',
      Type: 'String',
      Required: 'Yes',
      Description:
        'A unique ID for the site. The SDK uses this ID to identify the corresponding site.',
    },
    {
      'Property Name': 'disabledDefaultPrompt',
      Type: 'Boolean',
      Required: 'No',
      Description:
        'Determines whether the default prompt is displayed. When set to true, the default prompt will not be displayed to the user. The default value is false. This option provides site owners with the ability to control the display of the popup, allowing for custom triggering, such as a button or link click. Since its default value is false, the popup modal will appear by default.',
    },
    {
      'Property Name': 'segment',
      Type: 'String | String[]',
      Required: 'No',
      Description:
        'Allows customers to assign a segment or multiple segments to subscribers during the subscription process. For more details, refer to the <a href="#segment">Segment</a> section.',
    },
  ];
  
  export const subscriberProperties = [
    {
      'Property Name': 'subscriber_id',
      Type: 'String',
      Required: 'Yes',
      Description:
        'This represents a unique ID for each subscriber, generated by PushEngage using the subscription details. It identifies the subscriber and only changes if the subscription details change.',
    },
    {
      'Property Name': 'subscription_url',
      Type: 'String',
      Required: 'Yes',
      Description:
        'This is the URL where the subscriber opted in. It can be either a website URL or a landing page URL.',
    },
    {
      'Property Name': 'automated_notification',
      Type: 'Boolean',
      Required: 'Yes',
      Description:
        'Indicates if automated/personalized notifications for the user are enabled or disabled. Automated notifications cover all types of triggered campaigns. Further details are in the "<a href="#automatedpersonalized-notifications">Automated Notifications</a>" section.',
    },
    {
      'Property Name': 'browser',
      Type: 'String',
      Required: 'Yes',
      Description: 'This denotes the browser in which the subscriber opted in.',
    },
    {
      'Property Name': 'timezone',
      Type: 'String',
      Required: 'Yes',
      Description: `Display the subscriber's timezone. It updates automatically if the subscriber changes their timezone and revisits the site. The value is presented in the format +/-HH:MM.`,
    },
    {
      'Property Name': 'subscription_at',
      Type: 'String',
      Required: 'Yes',
      Description:
        'Indicates the subscription date of the subscriber, following the format YYYY-MM-DDTHH:MM:SSZ.',
    },
    {
      'Property Name': 'device',
      Type: 'String',
      Required: 'Yes',
      Description:
        'Denotes the device type from which the subscriber opted in, such as desktop or mobile.',
    },
    {
      'Property Name': 'attributes',
      Type: 'Object',
      Required: 'Yes',
      Description:
        'These are key-value pairs set by the site owner for the subscriber. The data can be any key-value format. If nothing is set, it defaults to an empty object. Further details are in the "<a href="#attributes">Attributes</a>" section.',
    },
    {
      'Property Name': 'segments',
      Type: 'String[]',
      Required: 'Yes',
      Description: `Segments target specific subscriber groups. This shows the names of the segments to which a subscriber belongs. If they aren't linked with any segment, it returns an empty array. Further details are in the "<a href="#segment">Segment</a>" section.`,
    },
    {
      'Property Name': 'country',
      Type: 'String',
      Required: 'No',
      Description:
        'Shows the country from which the subscriber opted in. It updates when they change their location and revisit the site. This detail is only accessible when "Enable Geolocation" is turned on in the "Site Details" dashboard.',
    },
    {
      'Property Name': 'state',
      Type: 'String',
      Required: 'No',
      Description: `Represents the state from which the subscriber opted in. It's updated when the subscriber changes location and revisits the site. This detail is accessible only when "Enable Geolocation" is turned on in the "Site Details" dashboard.`,
    },
    {
      'Property Name': 'city',
      Type: 'String',
      Required: 'No',
      Description: `Denotes the city from which the subscriber opted in. It's updated when the subscriber changes their location and revisits the site. This detail is accessible only when "Enable Geolocation" is enabled in the "Site Details" dashboard section.`,
    },
    {
      'Property Name': 'profile_id',
      Type: 'String',
      Required: 'No',
      Description:
        'This is the unique ID given to the subscriber by the site owner. More insights can be found in the "<a href="#profile-id-to-subscriber">Profile ID</a>" section.',
    },
  ];
  
  export const permissionPromptProperties = [
    {
      'Property Name': 'permission',
      Type: 'String',
      Required: 'Yes',
      Description: `Indicates the push notification permission status for the user. It can be one of the following values:
      <ul>
        <li><code>granted</code>: The user has granted permission to receive push notifications.</li>
        <li><code>denied</code>: The user has denied permission to receive push notifications.</li>
        <li><code>default</code>: The user has not yet granted or denied permission to receive push notifications.</li>
      </ul>`,
    },
    {
      'Property Name': 'is_permission_changed',
      Type: 'Boolean',
      Required: 'Yes',
      Description: `Indicates whether the user's permission status has changed. The possible values are:
      <ul>
        <li><code>true</code>: The user's permission status has changed.</li>
        <li><code>false</code>: The user's permission status remains the same.</li>
      </ul>
      For instance, if a user newly grants permission to receive push notifications, <code>is_permission_changed</code> will return <code>true</code>. However, if a user who has already granted permission attempts to subscribe again, <code>is_permission_changed</code> will return <code>false</code>.`,
    },
    {
      'Property Name': 'subscriber_id',
      Type: 'String',
      Required: 'No',
      Description:
        'Represents a unique ID for each subscriber, generated by PushEngage using the subscription details. This ID identifies the subscriber and only changes if the subscription details change. This information is available only when a subscriber is subscribed.',
    },
    {
      'Property Name': 'geo_info',
      Type: 'Object',
      Required: 'No',
      Description: 'Include the geo information like country, state, city.',
    },
    {
      'Property Name': 'geo_info.country',
      Type: 'String',
      Required: 'No',
      Description: `Denotes the country from which the subscriber opted in. It's updated when the subscriber changes their location and revisits the site. This detail is accessible only when "Enable Geolocation" is enabled in the "Site Details" dashboard section.`,
    },
    {
      'Property Name': 'geo_info.state',
      Type: 'String',
      Required: 'No',
      Description: `Represents the state from which the subscriber opted in. It's updated when the subscriber changes location and revisits the site. This detail is accessible only when "Enable Geolocation" is turned on in the "Site Details" dashboard.`,
    },
    {
      'Property Name': 'geo_info.city',
      Type: 'String',
      Required: 'No',
      Description: `Denotes the city from which the subscriber opted in. It's updated when the subscriber changes their location and revisits the site. This detail is accessible only when "Enable Geolocation" is enabled in the "Site Details" dashboard section.`,
    },
  ];
  
  export const identifyProperties = [
    {
      Key: 'first_name',
      Type: 'String',
      Required: 'No',
      Description:
        'The first name of the subscriber. The maximum length is 32 characters.',
    },
    {
      Key: 'last_name',
      Type: 'String',
      Required: 'No',
      Description:
        'The last name of the subscriber. The maximum length is 32 characters.',
    },
    {
      Key: 'email',
      Type: 'String',
      Required: 'No',
      Description:
        'The email address of the subscriber. The maximum length is 128 characters.',
    },
    {
      Key: 'phone',
      Type: 'String',
      Required: 'No',
      Description:
        'The phone number of the subscriber. It should be in <a href="/api/rest-api/e-164-phone-format/">E.164</a> format. Spaces are not allowed in the phone number.',
    },
    {
      Key: 'gender',
      Type: 'String',
      Required: 'No',
      Description:
        'The gender of the subscriber. It should be <code>male</code>, <code>female</code>, or <code>other</code>.',
    },
    {
      Key: 'dob',
      Type: 'String',
      Required: 'No',
      Description:
        'The date of birth of the subscriber. It should be in <a href="/api/rest-api/iso-8601-date-format/">ISO 8601</a> format.',
    },
    {
      Key: 'language',
      Type: 'String',
      Required: 'No',
      Description:
        'The language of the subscriber should be in <a href="/api/rest-api/iso-639-language-codes/">ISO 639-1 (Alpha-2)</a> codes. ISO 639-1 codes are two-letter codes that represent languages. It should be in lowercase. This field value is always available to subscribers by default.',
    },
    {
      Key: 'profile_id',
      Type: 'String',
      Required: 'No',
      Description:
        'The unique ID given to the subscriber by the site owner. The maximum length is 64 characters.',
    },
    {
      Key: 'country',
      Type: 'String',
      Required: 'No',
      Description: `The subscriber's country name (maximum length of 64 characters). PushEngage automatically captures this based on the subscriber's IP address. When updating manually, use title case for the country name (e.g., "India", "United States").`,
    },
    {
      Key: 'city',
      Type: 'String',
      Required: 'No',
      Description: `The subscriber's city name (maximum length of 64 characters). PushEngage automatically captures this based on the subscriber's IP address. When updating manually, use title case for the city name (e.g., "Mumbai", "New York").`,
    },
    {
      Key: 'state',
      Type: 'String',
      Required: 'No',
      Description: `The subscriber's state name (maximum length of 64 characters). PushEngage automatically captures this based on the subscriber's IP address. When updating manually, use title case for the state name (e.g., "Uttar Pradesh", "California").`,
    },
    {
      Key: 'zip',
      Type: 'String',
      Required: 'No',
      Description:
        'The zip code of the subscriber. The maximum length is 16 characters.',
    },
  ];